name: Build and publish

on:
  push:
    branches: [master]
    tags:
      - '*'

jobs:
  build_wheel:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install Python3 build package
        run: pip install build
      - name: Build wheel
        run: python -mbuild
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  publish:
    name: Publish to PyPi
    needs:
      - build_wheel
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mhdtools
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
